/*!40101 SET NAMES binary*/;
/*!40014 SET FOREIGN_KEY_CHECKS=0*/;

CREATE TABLE `wp_wplnst_urls_locations` (
  `loc_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `url_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `scan_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `link_type` varchar(25) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `object_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `object_type` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `object_post_type` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `object_field` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `object_date_gmt` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `detected_at` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `chunk` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `anchor` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `raw_url` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `fragment` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `spaced` tinyint(1) NOT NULL DEFAULT '0',
  `malformed` tinyint(1) NOT NULL DEFAULT '0',
  `absolute` tinyint(1) NOT NULL DEFAULT '0',
  `protorel` tinyint(1) NOT NULL DEFAULT '0',
  `relative` tinyint(1) NOT NULL DEFAULT '0',
  `nofollow` tinyint(1) NOT NULL DEFAULT '0',
  `ignored` tinyint(1) NOT NULL DEFAULT '0',
  `unlinked` tinyint(1) NOT NULL DEFAULT '0',
  `modified` tinyint(1) NOT NULL DEFAULT '0',
  `anchored` tinyint(1) NOT NULL DEFAULT '0',
  `attributed` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`loc_id`),
  KEY `url_id` (`url_id`),
  KEY `scan_id` (`scan_id`),
  KEY `link_type` (`link_type`),
  KEY `object_id` (`object_id`),
  KEY `object_type` (`object_type`),
  KEY `object_date_gmt` (`object_date_gmt`),
  KEY `anchor` (`anchor`(250)),
  KEY `spaced` (`spaced`),
  KEY `malformed` (`malformed`),
  KEY `absolute` (`absolute`),
  KEY `protorel` (`protorel`),
  KEY `relative` (`relative`),
  KEY `nofollow` (`nofollow`),
  KEY `ignored` (`ignored`),
  KEY `unlinked` (`unlinked`),
  KEY `modified` (`modified`),
  KEY `anchored` (`anchored`),
  KEY `attributed` (`attributed`)
) ENGINE=MyISAM AUTO_INCREMENT=139 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
