/*!40101 SET NAMES binary*/;
/*!40014 SET FOREIGN_KEY_CHECKS=0*/;
/*!40103 SET TIME_ZONE='+00:00' */;
INSERT INTO `wp_terms` VALUES
(1,"Uncategorized","uncategorized",0),
(2,"Main Nav","main-nav",0),
(3,"Top Secondary Nav","top-secondary-nav",0),
(4,"Footer Menu","footer-menu",0),
(5,"Home Featured Left","home-featured-left",0),
(6,"Home Featured Right","home-featured-right",0),
(7,"CCN MexicoReport™","ccn-mexico-report",0),
(8,"Mexican Energy Law","mexican-energy-law",0),
(9,"MexicanAutomotive","mexicanautomotive",0),
(10,"Legal Updates","legal-updates",0),
(11,"San Antonio","san-antonio",0),
(12,"Austin","austin",0),
(13,"Agriculture &amp; Ranching","agriculture",0),
(14,"Automotive","automotive-law",0),
(15,"Corporate","corporate",0),
(16,"Tax","tax",0),
(17,"Antitrust","antitrust",0),
(18,"Banking","banking",0),
(19,"Bankruptcy &amp; Restructurings","bankruptcy-restructurings",0),
(20,"Customs","customs",0),
(21,"Energy","energy",0),
(22,"Environmental","environmental",0),
(23,"Expert Witness","expert-witness",0),
(24,"Insurance","insurance",0),
(25,"Intellectual Property","intellectual-property",0),
(26,"International Trade","international-trade",0),
(27,"Invest in Texas","invest-in-texas",0),
(28,"Labor &amp; Employment","labor-employment",0),
(29,"Litigation","litigation",0),
(30,"Mergers &amp; Acquisitions","mergers-acquisitions",0),
(31,"Real Estate","real-estate",0),
(32,"Mobile Menu","mobile-menu",0),
(34,"CCN Mexico Report","ccn-mexico-report",0),
(35,"Legal Updates","legal-updates",0),
(36,"BUSINESS &amp; POLITICS OUTLOOK","business-politics-outlook",0),
(37,"error","error",0),
(38,"event","event",0),
(39,"ctct_activity","ctct_activity",0),
(40,"ctct_debug","ctct_debug",0),
(41,"ctct_error","ctct_error",0),
(42,"ctct_log","ctct_log",0),
(43,"McAllen","mcallen",0),
(44,"Mexico City","mexico-city",0),
(45,"Monterrey","monterrey",0),
(46,"Queretaro","queretaro",0),
(47,"Ciudad Juarez","ciudad-juarez",0),
(48,"Reynosa","reynosa",0),
(49,"Matamoros","matamoros",0),
(50,"Tijuana","tijuana",0),
(51,"Social Security","social-security",0),
(52,"Administrative Law","administrative-law",0),
(54,"Mexican Energy Law","mexican-energy-law-es",0),
(55,"CCN MexicoReport™","ccn-mexico-report-es",0),
(56,"MexicanAutomotive","mexicanautomotive-es",0),
(57,"Main Nav - Spanish","main-nav-spanish",0),
(58,"Top Secondary Nav - Spanish","top-secondary-nav-spanish",0),
(59,"Footer Menu - Spanish","footer-menu-spanish",0),
(60,"Mobile Menu - Spanish","mobile-menu-spanish",0),
(61,"Concursos Mercantiles y Reestructuraciones","concursos-mercantiles-y-reestructuraciones",0),
(62,"Corporativa","corporativa",0),
(63,"Energética","energetica",0),
(64,"Propiedad Intelectual","propiedad-intelectual",0),
(65,"Fusiones y Adquisiciones","fusiones-y-adquisiciones",0),
(66,"Mexico City","ciudad-de-mexico-es",0),
(67,"Aduanera","aduanera",0),
(68,"Comercio Internacional","comercio-internacional",0),
(69,"Inmobiliaria","inmobiliaria",0),
(70,"Fiscal","fiscal",0),
(71,"Queretaro","queretaro-es",0),
(72,"Laboral","laboral",0),
(73,"Ciudad Juarez","ciudad-juarez-es",0),
(74,"Automotriz","automotriz",0),
(75,"Competencia Económica","competencia-economica",0),
(76,"Litigio","litigio",0),
(77,"Tijuana","tijuana-es",0),
(78,"Monterrey","monterrey-es",0),
(79,"Matamoros","matamoros-es",0),
(80,"Reynosa","reynosa-es",0),
(81,"Seguros","seguros",0),
(82,"McAllen","mcallen-es",0),
(83,"Inversión en Texas","inversion-en-texas",0),
(84,"Ambiental","ambiental",0),
(85,"San Antonio","san-antonio-es",0),
(86,"Peritaje Jurídico","peritaje-juridico",0),
(87,"Bancaria y Financiera","bancaria-y-financiera",0),
(88,"Agrícola, Ganadera, Cinegética y Silvícola","agricola-ganadera-cinegetica-y-silvicola",0),
(89,"Austin","austin-es",0),
(90,"Ley administrativa","ley-administrativa",0),
(91,"Seguro Social","seguro-social",0),
(92,"Business &amp; Politics Outlook","business-politics-outlook",0),
(93,"Economic Indicators","economic-indicators",0),
(94,"Política y Negocios","business-politics-outlook-es",0),
(95,"Indicadores Económicos","economic-indicators-es",0),
(96,"Actualización Legal","legal-updates-es",0),
(97,"Guadalajara","guadalajara",0),
(98,"International Trade and Customs","international-trade-and-customs",0),
(99,"Comercio Internacional y Aduanera","comercio-internacional-y-aduanera",0),
(100,"Home Featured Center","home-featured-center",0),
(101,"Immigration","immigration",0),
(102,"Immigration","immigration-es",0),
(104,"カテゴリーなし","%e3%82%ab%e3%83%86%e3%82%b4%e3%83%aa%e3%83%bc%e3%81%aa%e3%81%97",0),
(105,"Main Menu - Japones","main-menu-japones",0),
(106,"Home Featured Left","home-featured-left-jp",0),
(107,"Main Nav - Japanese","main-nav-japanese",0),
(108,"Top Secondary Nav - Japanese","top-secondary-nav-japanese",0),
(109,"Footer Menu - Japanese","footer-menu-japanese",0),
(110,"Mobile Menu - Japanese","mobile-menu-japanese",0),
(111,"Home Featured Left","home-featured-left-es",0),
(112,"Home Featured Right","home-featured-right-es",0),
(113,"Guadalajara","guadalajara-es",0),
(114,"Home Featured Right","home-featured-right-jp",0),
(115,"home-featured-center-jp","home-featured-center-jp",0),
(116,"ニュースレター","%e3%83%8b%e3%83%a5%e3%83%bc%e3%82%b9%e3%83%ac%e3%82%bf%e3%83%bc",0),
(117,"Issue #148","issue-148",0);
